"""initial

Revision ID: d3988b754a62
Revises: 
Create Date: 2025-09-16 23:14:55.457166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3988b754a62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='ID пользователя'),
    sa.Column('full_name', sa.String(), nullable=True, comment='Полное имя'),
    sa.Column('sign', sa.Enum('ARIES', 'TAURUS', 'GEMINI', 'CANCE', 'LEO', 'VIRGO', 'LIBRA', 'SCORPIO', 'SAGITTARIUS', 'CAPRICORN', 'AQUARIUS', 'PISCES', name='sign'), nullable=False, comment='Знак зодиака'),
    sa.Column('company_role', sa.Enum('SYS_ANALYST', 'BUSINESS_ANALYST', 'ARCHITECT', 'BACKEND', 'FRONTEND', 'DESIGNER', 'QA_ENGINEER', 'DEVOPS_ENGINEER', 'CLIENT', 'DATA_SCIENTIST', 'TEAM_LEAD', 'MANAGER', 'DB_SPECIALIST',  name='companyrole'), nullable=False, comment='Роль в компании'),
    sa.Column('emoji', sa.String(length=128), nullable=False, comment='HTML-код emoji'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Uuid(), nullable=False, comment='ID предсказания'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='ID пользователя'),
    sa.Column('date', sa.Date(), nullable=False, comment='День предсказания'),
    sa.Column('predict', sa.Text(), nullable=False, comment='Предсказание'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_date', 'predictions', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_date', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('users')
    # ### end Alembic commands ###
